from pathlib import Path
from typing import Protocol, runtime_checkable

from shared.adapters.types import Judgment, PostMeta, PostReceipt, Visibility


@runtime_checkable
class DistributionAdapter(Protocol):
    def publish(self, render: Path, meta: PostMeta) -> PostReceipt: ...
    def confirm_posted(self, video_id: str, platform: str) -> PostReceipt | None: ...
    def allowed_visibility(self, audit_state: str) -> set[Visibility]: ...


@runtime_checkable
class ModelBackend(Protocol):
    def generate_image(self, prompt: str, seed: int) -> Path: ...
    def img2vid(self, image: Path, seed: int) -> Path: ...
    def tts(self, text: str) -> Path: ...
    # seed -> reproducible best-of-N (ADR 0009)
    def llm(self, prompt: str, seed: int | None = None) -> str: ...
    # constrained JSON + bounded retry (malformed JSON is the #1 local-LLM failure)
    def llm_json(self, prompt: str, seed: int | None = None) -> dict: ...
    def vlm_judge(self, frames: list[Path], script: dict) -> Judgment: ...
    def restore(self, frames: list[Path]) -> list[Path]: ...   # ESRGAN/RIFE/GFPGAN (01d, M2)


@runtime_checkable
class LayoutEngine(Protocol):
    def render(self, render_manifest: dict) -> list[Path]: ...
